/**
 * Demo data shown when the backend API is unreachable (e.g. Vercel static deploy).
 * All CVE IDs and descriptions are real; asset names are illustrative.
 */

export const mockStats = {
  total_assets: 8,
  total_threats: 118,
  critical_threats: 14,
  active_exploits: 23,
  pending_briefings: 7,
  resolved_briefings: 3,
  severity_breakdown: { critical: 14, high: 38, medium: 47, low: 19 },
  source_breakdown: { nvd: 20, cisa_kev: 30, exploitdb: 19, github: 20, shodan: 9, greynoise: 20 },
};

export const mockAssets = [
  { id: 1, name: 'Web Server (Apache)', type: 'server', vendor: 'Apache', product: 'HTTP Server', version: '2.4.51', port: 443, network: '10.0.1.0/24', created_at: '2026-02-05T10:00:00Z' },
  { id: 2, name: 'API Gateway (nginx)', type: 'server', vendor: 'nginx', product: 'nginx', version: '1.21.6', port: 8443, network: '10.0.1.0/24', created_at: '2026-02-05T10:01:00Z' },
  { id: 3, name: 'PostgreSQL Primary', type: 'database', vendor: 'PostgreSQL', product: 'postgresql', version: '14.2', port: 5432, network: '10.0.2.0/24', created_at: '2026-02-05T10:02:00Z' },
  { id: 4, name: 'Redis Cache', type: 'database', vendor: 'Redis', product: 'redis', version: '7.0.5', port: 6379, network: '10.0.2.0/24', created_at: '2026-02-05T10:03:00Z' },
  { id: 5, name: 'Jenkins CI', type: 'application', vendor: 'Jenkins', product: 'jenkins', version: '2.375.1', port: 8080, network: '10.0.3.0/24', created_at: '2026-02-05T10:04:00Z' },
  { id: 6, name: 'Grafana Monitoring', type: 'application', vendor: 'Grafana', product: 'grafana', version: '9.3.2', port: 3000, network: '10.0.3.0/24', created_at: '2026-02-05T10:05:00Z' },
  { id: 7, name: 'OpenSSH Bastion', type: 'server', vendor: 'OpenBSD', product: 'openssh', version: '8.9p1', port: 22, network: '10.0.0.0/24', created_at: '2026-02-05T10:06:00Z' },
  { id: 8, name: 'Kubernetes Node', type: 'cloud', vendor: 'Kubernetes', product: 'kubelet', version: '1.26.1', port: 10250, network: '10.0.4.0/24', created_at: '2026-02-05T10:07:00Z' },
];

export const mockThreats = [
  { id: 1, source: 'cisa_kev', source_id: 'CVE-2024-3400', title: 'Palo Alto Networks PAN-OS Command Injection Vulnerability', description: 'A command injection vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS allows unauthenticated attackers to execute arbitrary code with root privileges.', severity: 'critical', cvss_score: 10.0, affected_vendor: 'Palo Alto Networks', affected_product: 'PAN-OS', affected_version: '<10.2.9-h1', exploits_available: true, actively_exploited: true, published_date: '2024-04-12T00:00:00Z', created_at: '2026-02-05T12:00:00Z' },
  { id: 2, source: 'nvd', source_id: 'CVE-2024-21762', title: 'Fortinet FortiOS Out-of-Bound Write Vulnerability', description: 'An out-of-bound write vulnerability in FortiOS SSL VPN may allow a remote unauthenticated attacker to execute arbitrary code via specially crafted HTTP requests.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'Fortinet', affected_product: 'FortiOS', affected_version: '<7.4.2', exploits_available: true, actively_exploited: true, published_date: '2024-02-09T00:00:00Z', created_at: '2026-02-05T12:01:00Z' },
  { id: 3, source: 'shodan', source_id: 'CVE-2023-44487', title: 'HTTP/2 Rapid Reset Attack (DDoS)', description: 'The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset many streams quickly. Exploited in the wild as the largest DDoS attack ever recorded.', severity: 'high', cvss_score: 7.5, affected_vendor: 'Multiple', affected_product: 'HTTP/2', affected_version: 'All', exploits_available: true, actively_exploited: true, published_date: '2023-10-10T00:00:00Z', created_at: '2026-02-05T12:02:00Z' },
  { id: 4, source: 'github', source_id: 'CVE-2024-27198', title: 'JetBrains TeamCity Authentication Bypass', description: 'Authentication bypass allowing unauthenticated attacker to reach internal API endpoints in JetBrains TeamCity server. Allows full server compromise including RCE.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'JetBrains', affected_product: 'TeamCity', affected_version: '<2023.11.4', exploits_available: true, actively_exploited: true, published_date: '2024-03-04T00:00:00Z', created_at: '2026-02-05T12:03:00Z' },
  { id: 5, source: 'exploitdb', source_id: 'CVE-2024-1709', title: 'ConnectWise ScreenConnect Authentication Bypass', description: 'Authentication bypass vulnerability in ConnectWise ScreenConnect allows an attacker to directly access confidential information or critical systems.', severity: 'critical', cvss_score: 10.0, affected_vendor: 'ConnectWise', affected_product: 'ScreenConnect', affected_version: '<23.9.8', exploits_available: true, actively_exploited: true, published_date: '2024-02-19T00:00:00Z', created_at: '2026-02-05T12:04:00Z' },
  { id: 6, source: 'greynoise', source_id: 'CVE-2024-0012', title: 'Palo Alto Networks PAN-OS Management Interface Auth Bypass', description: 'An authentication bypass in Palo Alto Networks PAN-OS management web interface allows an unauthenticated attacker with network access to gain administrator privileges.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'Palo Alto Networks', affected_product: 'PAN-OS', affected_version: '<11.2.4-h1', exploits_available: true, actively_exploited: true, published_date: '2024-11-18T00:00:00Z', created_at: '2026-02-05T12:05:00Z' },
  { id: 7, source: 'nvd', source_id: 'CVE-2024-47575', title: 'Fortinet FortiManager Missing Authentication for Critical Function', description: 'A missing authentication vulnerability in FortiManager fgfmd daemon may allow a remote unauthenticated attacker to execute arbitrary code or commands via specially crafted requests.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'Fortinet', affected_product: 'FortiManager', affected_version: '<7.6.1', exploits_available: true, actively_exploited: true, published_date: '2024-10-23T00:00:00Z', created_at: '2026-02-05T12:06:00Z' },
  { id: 8, source: 'cisa_kev', source_id: 'CVE-2023-46805', title: 'Ivanti Connect Secure Authentication Bypass', description: 'An authentication bypass vulnerability in the web component of Ivanti Connect Secure and Ivanti Policy Secure allows a remote attacker to access restricted resources by bypassing control checks.', severity: 'critical', cvss_score: 8.2, affected_vendor: 'Ivanti', affected_product: 'Connect Secure', affected_version: '<22.7R2.5', exploits_available: true, actively_exploited: true, published_date: '2024-01-10T00:00:00Z', created_at: '2026-02-05T12:07:00Z' },
  { id: 9, source: 'nvd', source_id: 'CVE-2024-6387', title: 'OpenSSH regreSSHion - Remote Code Execution', description: 'A signal handler race condition was found in sshd in OpenSSH, where a client does not authenticate within LoginGraceTime seconds. A remote unauthenticated attacker may exploit this to execute arbitrary code as root.', severity: 'high', cvss_score: 8.1, affected_vendor: 'OpenBSD', affected_product: 'openssh', affected_version: '<9.8p1', exploits_available: true, actively_exploited: false, published_date: '2024-07-01T00:00:00Z', created_at: '2026-02-05T12:08:00Z' },
  { id: 10, source: 'exploitdb', source_id: 'CVE-2024-23897', title: 'Jenkins Arbitrary File Read via CLI', description: 'Jenkins uses the args4j library to parse command arguments. This command parser has a feature that replaces file paths with the contents of the file, allowing unauthenticated attackers to read arbitrary files.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'Jenkins', affected_product: 'jenkins', affected_version: '<2.442', exploits_available: true, actively_exploited: true, published_date: '2024-01-24T00:00:00Z', created_at: '2026-02-05T12:09:00Z' },
  { id: 11, source: 'github', source_id: 'CVE-2024-4577', title: 'PHP CGI Argument Injection (XAMPP)', description: 'PHP CGI implementations on Windows fail to properly handle certain character sequences, allowing unauthenticated remote attackers to bypass CVE-2012-1823 protections and execute arbitrary code.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'PHP', affected_product: 'php', affected_version: '<8.3.8', exploits_available: true, actively_exploited: true, published_date: '2024-06-09T00:00:00Z', created_at: '2026-02-05T12:10:00Z' },
  { id: 12, source: 'shodan', source_id: 'CVE-2024-21887', title: 'Ivanti Connect Secure Command Injection', description: 'A command injection vulnerability in web components of Ivanti Connect Secure and Ivanti Policy Secure allows an authenticated administrator to send specially crafted requests and execute arbitrary commands.', severity: 'critical', cvss_score: 9.1, affected_vendor: 'Ivanti', affected_product: 'Connect Secure', affected_version: '<22.7R2.5', exploits_available: true, actively_exploited: true, published_date: '2024-01-12T00:00:00Z', created_at: '2026-02-05T12:11:00Z' },
  { id: 13, source: 'cisa_kev', source_id: 'CVE-2024-38812', title: 'VMware vCenter Server Heap Overflow', description: 'The VMware vCenter Server contains a heap-overflow vulnerability in the implementation of the DCERPC protocol. A malicious actor with network access may trigger a heap overflow leading to remote code execution.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'VMware', affected_product: 'vCenter Server', affected_version: '<8.0U3b', exploits_available: true, actively_exploited: true, published_date: '2024-09-17T00:00:00Z', created_at: '2026-02-05T12:12:00Z' },
  { id: 14, source: 'greynoise', source_id: 'CVE-2024-29824', title: 'Ivanti EPM SQL Injection', description: 'An unspecified SQL Injection vulnerability in Core server of Ivanti EPM allows an unauthenticated attacker within the same network to execute arbitrary code.', severity: 'critical', cvss_score: 9.6, affected_vendor: 'Ivanti', affected_product: 'Endpoint Manager', affected_version: '<2022SU5', exploits_available: true, actively_exploited: true, published_date: '2024-05-31T00:00:00Z', created_at: '2026-02-05T12:13:00Z' },
  { id: 15, source: 'nvd', source_id: 'CVE-2024-3094', title: 'XZ Utils Backdoor (liblzma)', description: 'Malicious code was discovered in the upstream tarballs of xz/liblzma starting from version 5.6.0. The backdoor manipulates sshd via systemd, potentially allowing unauthorized remote access.', severity: 'critical', cvss_score: 10.0, affected_vendor: 'Tukaani', affected_product: 'xz', affected_version: '5.6.0-5.6.1', exploits_available: true, actively_exploited: false, published_date: '2024-03-29T00:00:00Z', created_at: '2026-02-05T12:14:00Z' },
  { id: 16, source: 'nvd', source_id: 'CVE-2023-4966', title: 'Citrix NetScaler ADC Buffer Overflow (CitrixBleed)', description: 'Sensitive information disclosure in NetScaler ADC and NetScaler Gateway when configured as a Gateway or AAA virtual server. Exploited in the wild allowing session hijacking.', severity: 'high', cvss_score: 7.5, affected_vendor: 'Citrix', affected_product: 'NetScaler ADC', affected_version: '<14.1-8.50', exploits_available: true, actively_exploited: true, published_date: '2023-10-10T00:00:00Z', created_at: '2026-02-05T12:15:00Z' },
  { id: 17, source: 'exploitdb', source_id: 'CVE-2024-50623', title: 'Cleo Harmony/VLTrader/LexiCom Unrestricted File Upload', description: 'Cleo Harmony, VLTrader, and LexiCom allow unrestricted file upload and download, which can lead to remote code execution. Actively exploited by ransomware groups.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'Cleo', affected_product: 'Harmony', affected_version: '<5.8.0.21', exploits_available: true, actively_exploited: true, published_date: '2024-10-28T00:00:00Z', created_at: '2026-02-05T12:16:00Z' },
  { id: 18, source: 'github', source_id: 'CVE-2024-28255', title: 'OpenMetadata Authentication Bypass', description: 'OpenMetadata is a unified platform for discovery, observability, and governance. A flaw in the JWT authentication mechanism allows attackers to bypass authentication entirely.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'OpenMetadata', affected_product: 'openmetadata', affected_version: '<1.2.4', exploits_available: true, actively_exploited: false, published_date: '2024-03-15T00:00:00Z', created_at: '2026-02-05T12:17:00Z' },
  { id: 19, source: 'cisa_kev', source_id: 'CVE-2024-20353', title: 'Cisco ASA and FTD Denial of Service', description: 'A vulnerability in the management and VPN web servers for Cisco ASA and FTD software could allow an unauthenticated remote attacker to cause the device to reload unexpectedly, resulting in DoS.', severity: 'high', cvss_score: 8.6, affected_vendor: 'Cisco', affected_product: 'ASA', affected_version: 'Multiple', exploits_available: true, actively_exploited: true, published_date: '2024-04-24T00:00:00Z', created_at: '2026-02-05T12:18:00Z' },
  { id: 20, source: 'greynoise', source_id: 'CVE-2024-36401', title: 'GeoServer OGC Filter Evaluation RCE', description: 'GeoServer evaluates property/attribute names as XPath expressions, which can be abused to execute arbitrary code via OGC filter evaluation. Critical RCE in geospatial servers.', severity: 'critical', cvss_score: 9.8, affected_vendor: 'GeoServer', affected_product: 'geoserver', affected_version: '<2.23.6', exploits_available: true, actively_exploited: true, published_date: '2024-07-01T00:00:00Z', created_at: '2026-02-05T12:19:00Z' },
  { id: 21, source: 'nvd', source_id: 'CVE-2024-9264', title: 'Grafana SQL Expressions Code Injection', description: 'The SQL Expressions experimental feature of Grafana allows evaluation of duckdb queries containing user input. Insufficient sanitization leads to command injection and local file inclusion.', severity: 'critical', cvss_score: 9.9, affected_vendor: 'Grafana', affected_product: 'grafana', affected_version: '11.0.0-11.2.1', exploits_available: true, actively_exploited: false, published_date: '2024-10-18T00:00:00Z', created_at: '2026-02-05T12:20:00Z' },
  { id: 22, source: 'shodan', source_id: 'CVE-2024-24919', title: 'Check Point Quantum Gateway Information Disclosure', description: 'Potentially allowing an attacker to read certain information on Check Point Security Gateways once connected to the internet and enabled with remote Access VPN or Mobile Access Software Blades.', severity: 'high', cvss_score: 8.6, affected_vendor: 'Check Point', affected_product: 'Quantum Gateway', affected_version: 'R81.20', exploits_available: true, actively_exploited: true, published_date: '2024-05-28T00:00:00Z', created_at: '2026-02-05T12:21:00Z' },
  { id: 23, source: 'nvd', source_id: 'CVE-2024-21626', title: 'runc Container Escape via File Descriptor Leak', description: 'runc is a CLI tool for spawning and running containers. An internal file descriptor leak allows a container to gain access to the host filesystem. Affects Docker and Kubernetes.', severity: 'high', cvss_score: 8.6, affected_vendor: 'Open Containers', affected_product: 'runc', affected_version: '<1.1.12', exploits_available: true, actively_exploited: false, published_date: '2024-01-31T00:00:00Z', created_at: '2026-02-05T12:22:00Z' },
  { id: 24, source: 'exploitdb', source_id: 'CVE-2023-22527', title: 'Atlassian Confluence Template Injection RCE', description: 'A template injection vulnerability in out-of-date Confluence Data Center and Server allows unauthenticated remote code execution on affected instances.', severity: 'critical', cvss_score: 10.0, affected_vendor: 'Atlassian', affected_product: 'Confluence', affected_version: '<8.5.4', exploits_available: true, actively_exploited: true, published_date: '2024-01-16T00:00:00Z', created_at: '2026-02-05T12:23:00Z' },
];

export const mockBriefings = [
  {
    id: 1, threat_id: 9, asset_id: 7, priority_score: 9.2, status: 'new',
    summary: 'Critical OpenSSH vulnerability (regreSSHion) directly affects the bastion host running OpenSSH 8.9p1. A race condition in the sshd signal handler allows unauthenticated remote attackers to gain root access. The bastion host is the primary entry point to the internal network — compromise here would grant lateral movement to all internal segments.',
    remediation: '1. Immediately upgrade OpenSSH to version 9.8p1 or later on the bastion host\n2. As a temporary mitigation, set LoginGraceTime to 0 in sshd_config (note: this creates DoS risk)\n3. Implement IP allowlisting on the bastion host to restrict SSH access to known source IPs\n4. Deploy network-level monitoring for anomalous SSH connection patterns\n5. Audit authorized_keys files across all hosts for unauthorized entries',
    business_impact: 'The bastion host is the single entry point for administrative access to the entire infrastructure. Exploitation would give attackers root access to a machine that can reach every network segment (10.0.0.0/24 through 10.0.4.0/24), enabling data exfiltration, ransomware deployment, or persistent backdoor installation.',
    threat: { id: 9, source_id: 'CVE-2024-6387', severity: 'high', title: 'OpenSSH regreSSHion - Remote Code Execution' },
    asset: { id: 7, name: 'OpenSSH Bastion', version: '8.9p1', vendor: 'OpenBSD' },
    created_at: '2026-02-05T14:00:00Z',
  },
  {
    id: 2, threat_id: 10, asset_id: 5, priority_score: 9.0, status: 'new',
    summary: 'Jenkins 2.375.1 is vulnerable to CVE-2024-23897, an arbitrary file read vulnerability via the CLI. Unauthenticated attackers can read system files including /etc/passwd and Jenkins secrets. Combined with other techniques, this leads to full remote code execution on the CI server.',
    remediation: '1. Upgrade Jenkins to version 2.442 or later (LTS: 2.440.1+)\n2. Disable the Jenkins CLI if not actively used (-Dhudson.cli.CLICommand.allowAtController=false)\n3. Restrict network access to Jenkins to trusted developer networks only\n4. Rotate all credentials stored in Jenkins (API tokens, SSH keys, cloud provider keys)\n5. Review Jenkins build logs for evidence of unauthorized file reads',
    business_impact: 'The Jenkins CI server holds deployment credentials, source code access, and cloud provider keys. Compromise leads to supply chain attacks through tampered builds, credential theft enabling cloud infrastructure takeover, and intellectual property exposure. This is a Tier-1 critical asset.',
    threat: { id: 10, source_id: 'CVE-2024-23897', severity: 'critical', title: 'Jenkins Arbitrary File Read via CLI' },
    asset: { id: 5, name: 'Jenkins CI', version: '2.375.1', vendor: 'Jenkins' },
    created_at: '2026-02-05T14:01:00Z',
  },
  {
    id: 3, threat_id: 21, asset_id: 6, priority_score: 8.7, status: 'acknowledged',
    summary: 'Grafana 9.3.2 is affected by CVE-2024-9264, a critical code injection via SQL Expressions. While the SQL Expressions feature is experimental and not enabled by default, if DuckDB is installed on the server, any Grafana Viewer can execute system commands and read local files through crafted queries.',
    remediation: '1. Upgrade Grafana to version 11.2.2 or later\n2. If immediate upgrade is not possible, remove DuckDB from the Grafana server\n3. Disable the SQL Expressions experimental feature via configuration\n4. Audit Grafana user permissions and remove unnecessary Viewer accounts\n5. Monitor Grafana server logs for unusual SQL expression evaluations',
    business_impact: 'Grafana has visibility into all monitoring data including infrastructure metrics, application logs, and potentially sensitive business KPIs. Code execution on the monitoring server could expose internal architecture details, enable pivot attacks, and allow manipulation of monitoring data to mask ongoing intrusions.',
    threat: { id: 21, source_id: 'CVE-2024-9264', severity: 'critical', title: 'Grafana SQL Expressions Code Injection' },
    asset: { id: 6, name: 'Grafana Monitoring', version: '9.3.2', vendor: 'Grafana' },
    created_at: '2026-02-05T14:02:00Z',
  },
  {
    id: 4, threat_id: 23, asset_id: 8, priority_score: 8.4, status: 'new',
    summary: 'Kubernetes kubelet 1.26.1 is potentially affected by CVE-2024-21626, a container escape vulnerability in runc. An attacker who can create or modify containers could escape to the host filesystem through leaked file descriptors, gaining full node access.',
    remediation: '1. Update runc to version 1.1.12 or later on all Kubernetes nodes\n2. Upgrade containerd to 1.6.28+ or 1.7.13+ which bundles the fixed runc\n3. Restrict who can create pods via RBAC — limit to trusted service accounts\n4. Enable Pod Security Standards (restricted profile) to prevent privileged containers\n5. Audit existing pod specs for containers running with elevated privileges',
    business_impact: 'Container escape on a Kubernetes node grants the attacker host-level access to the node and potentially all pods running on it. Given the node is in the 10.0.4.0/24 network, lateral movement to other cluster nodes is possible. Workloads running on the cluster, including internal services and data pipelines, would be fully compromised.',
    threat: { id: 23, source_id: 'CVE-2024-21626', severity: 'high', title: 'runc Container Escape via File Descriptor Leak' },
    asset: { id: 8, name: 'Kubernetes Node', version: '1.26.1', vendor: 'Kubernetes' },
    created_at: '2026-02-05T14:03:00Z',
  },
  {
    id: 5, threat_id: 3, asset_id: 2, priority_score: 7.8, status: 'in_progress',
    summary: 'nginx 1.21.6 supports HTTP/2 and is vulnerable to the Rapid Reset attack (CVE-2023-44487). While primarily a DoS vector, this vulnerability was used in the largest DDoS attack ever recorded. The API gateway is a public-facing endpoint and a prime target.',
    remediation: '1. Upgrade nginx to version 1.25.3 or later which includes HTTP/2 Rapid Reset mitigations\n2. Configure limit_conn and limit_req directives to rate-limit HTTP/2 streams per connection\n3. Deploy a DDoS protection service (Cloudflare, AWS Shield) in front of the gateway\n4. Set http2_max_concurrent_streams to a conservative value (e.g., 128)\n5. Monitor for anomalous HTTP/2 RST_STREAM frame rates',
    business_impact: 'The API gateway handles all external API traffic. A successful Rapid Reset DDoS attack would render all customer-facing services unavailable. Revenue loss during downtime is estimated at significant levels depending on traffic volume, plus SLA violation penalties for enterprise customers.',
    threat: { id: 3, source_id: 'CVE-2023-44487', severity: 'high', title: 'HTTP/2 Rapid Reset Attack (DDoS)' },
    asset: { id: 2, name: 'API Gateway (nginx)', version: '1.21.6', vendor: 'nginx' },
    created_at: '2026-02-05T14:04:00Z',
  },
  {
    id: 6, threat_id: 1, asset_id: 1, priority_score: 6.5, status: 'resolved',
    summary: 'While CVE-2024-3400 targets Palo Alto PAN-OS and not Apache HTTP Server directly, the threat intelligence indicates active mass exploitation campaigns targeting internet-facing services. The Apache web server should be verified as not proxying through any PAN-OS GlobalProtect instances.',
    remediation: '1. Verify that no Palo Alto PAN-OS firewalls sit in front of the Apache web server\n2. Ensure Apache is updated to the latest 2.4.x release for general hardening\n3. Review firewall rules to confirm the web server is only exposing necessary ports\n4. Implement WAF rules to detect command injection attempts in HTTP headers',
    business_impact: 'Low direct impact as this CVE targets PAN-OS, not Apache. However, if any Palo Alto firewalls protect this server, they could be exploited for full network bypass. Included for situational awareness of the active campaign.',
    threat: { id: 1, source_id: 'CVE-2024-3400', severity: 'critical', title: 'Palo Alto Networks PAN-OS Command Injection Vulnerability' },
    asset: { id: 1, name: 'Web Server (Apache)', version: '2.4.51', vendor: 'Apache' },
    created_at: '2026-02-05T14:05:00Z',
  },
  {
    id: 7, threat_id: 15, asset_id: 7, priority_score: 6.2, status: 'resolved',
    summary: 'The XZ Utils backdoor (CVE-2024-3094) was discovered in versions 5.6.0-5.6.1 of xz/liblzma. The bastion host running OpenSSH should be checked to verify that the system xz version is not in the affected range. Most stable distributions were not affected as they shipped older versions.',
    remediation: '1. Check the xz version on the bastion host: xz --version\n2. If version 5.6.0 or 5.6.1 is installed, immediately downgrade to 5.4.x\n3. Verify the package came from official distribution repositories\n4. Check sshd for unusual behavior or unexpected network connections\n5. Review system logs for signs of compromise during the exposure window',
    business_impact: 'If the compromised xz version was installed, attackers could have achieved unauthorized remote access via the sshd backdoor. The bastion host is the administrative gateway — full compromise would enable access to all internal systems without detection.',
    threat: { id: 15, source_id: 'CVE-2024-3094', severity: 'critical', title: 'XZ Utils Backdoor (liblzma)' },
    asset: { id: 7, name: 'OpenSSH Bastion', version: '8.9p1', vendor: 'OpenBSD' },
    created_at: '2026-02-05T14:06:00Z',
  },
];

export const mockRecent = mockBriefings.slice(0, 6);
